#!/bin/sh
target=/etc/cron.hourly/nicoanime_feed
bundle install
cat <<EOT|sudo tee $target
#!/bin/sh
`which ruby` /var/www/nicoanime_feed/nicoanime_feed.rb
EOT
sudo chmod +x $target
sudo ln -s /var/www/nicoanime_feed/nicoanime_feed.conf /etc/apache2/conf-enabled
sudo service apache2 restart
echo '初期データ生成...'
$target

